-- MySQL Script generated by MySQL Workbench
-- Thu May 11 13:50:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`turmaNODE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmaNODE` (
  `idturma` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idturma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AlunoNODE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AlunoNODE` (
  `idAluno` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `tipo_aluno` VARCHAR(45) NULL,
  `tipoBolsa` VARCHAR(45) NULL,
  `vaorMenalidade` DECIMAL(9,2) NULL,
  `idturma` INT NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `fk_AlunoNODE_turmaNODE_idx` (`idturma` ASC) VISIBLE,
  CONSTRAINT `fk_AlunoNODE_turmaNODE`
    FOREIGN KEY (`idturma`)
    REFERENCES `mydb`.`turmaNODE` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
